from __future__ import unicode_literals

SCENARIOS = [
    # ============================================================
    # ERROR-PATH SCENARIOS — every AI flag with no API key
    # ============================================================
    {
        "name": "explain_no_key",
        "args": ["--explain", "EMPTY", "EMPTY"],
        "env": {},
        "load_config_return": None,
        "mock_anthropic": False,
        "mock_import_error": False,
        "mock_runtime_error": False,
        "mock_inspector": False,
        "needs_postgres": False,
        "description": "--explain with no API key -> error on stderr, exit 1",
    },
    {
        "name": "explain_missing_package",
        "args": ["--explain", "EMPTY", "EMPTY"],
        "env": {"ANTHROPIC_API_KEY": "sk-ant-test"},
        "load_config_return": None,
        "mock_anthropic": False,
        "mock_import_error": True,
        "mock_runtime_error": False,
        "mock_inspector": False,
        "needs_postgres": False,
        "description": "--explain without anthropic package -> ImportError, exit 1",
    },
    {
        "name": "rollback_no_key",
        "args": ["EMPTY", "EMPTY", "--rollback"],
        "env": {},
        "load_config_return": None,
        "mock_anthropic": False,
        "mock_import_error": False,
        "mock_runtime_error": False,
        "mock_inspector": False,
        "needs_postgres": False,
        "description": "--rollback with no API key -> error on stderr, exit 1",
    },
    {
        "name": "advise_no_key",
        "args": ["--advise", "EMPTY", "EMPTY"],
        "env": {},
        "load_config_return": None,
        "mock_anthropic": False,
        "mock_import_error": False,
        "mock_runtime_error": False,
        "mock_inspector": False,
        "needs_postgres": False,
        "description": "--advise with no API key -> error on stderr, exit 1",
    },
    {
        "name": "generate_no_key",
        "args": ["--generate", "add an email column to users", "EMPTY"],
        "env": {},
        "load_config_return": None,
        "mock_anthropic": False,
        "mock_import_error": False,
        "mock_runtime_error": False,
        "mock_inspector": False,
        "needs_postgres": False,
        "description": "--generate with no API key -> error on stderr, exit 1",
    },
    {
        "name": "explain_drift_no_key",
        "args": [
            "--explain-drift",
            "--from-db",
            "postgresql://localhost/old",
            "--to-db",
            "postgresql://localhost/new",
        ],
        "env": {},
        "load_config_return": None,
        "mock_anthropic": False,
        "mock_import_error": False,
        "mock_runtime_error": False,
        "mock_inspector": False,
        "needs_postgres": False,
        "description": "--explain-drift with no API key -> error on stderr, exit 1",
    },
    {
        "name": "explain_drift_missing_package",
        "args": [
            "--explain-drift",
            "--from-db",
            "postgresql://localhost/old",
            "--to-db",
            "postgresql://localhost/new",
        ],
        "env": {"ANTHROPIC_API_KEY": "sk-ant-test"},
        "load_config_return": None,
        "mock_anthropic": False,
        "mock_import_error": True,
        "mock_runtime_error": False,
        "mock_inspector": False,
        "needs_postgres": False,
        "description": "--explain-drift without anthropic package -> ImportError, exit 1",
    },
    {
        "name": "explain_drift_runtime_error",
        "args": [
            "--explain-drift",
            "--from-db",
            "postgresql://localhost/old",
            "--to-db",
            "postgresql://localhost/new",
            "--api-key",
            "sk-ant-test",
        ],
        "env": {},
        "load_config_return": None,
        "mock_anthropic": True,
        "mock_import_error": False,
        "mock_runtime_error": True,
        "mock_inspector": True,
        "needs_postgres": False,
        "description": "--explain-drift with RuntimeError from Anthropic -> exit 1",
    },
    # ============================================================
    # SUCCESS-PATH SCENARIOS — empty diff with mocked Anthropic
    # ============================================================
    {
        "name": "explain_empty_diff",
        "args": ["--explain", "EMPTY", "EMPTY"],
        "env": {"ANTHROPIC_API_KEY": "sk-ant-test"},
        "load_config_return": None,
        "mock_anthropic": True,
        "mock_import_error": False,
        "mock_runtime_error": False,
        "mock_inspector": False,
        "needs_postgres": False,
        "mock_anthropic_response": "Safe migration. Adds a column. Overall risk: LOW",
        "description": "--explain on identical schemas -> 'No differences', exit 0",
    },
    {
        "name": "explain_json_empty_diff",
        "args": ["--explain", "--output", "json", "EMPTY", "EMPTY"],
        "env": {"ANTHROPIC_API_KEY": "sk-ant-test"},
        "load_config_return": None,
        "mock_anthropic": True,
        "mock_import_error": False,
        "mock_runtime_error": False,
        "mock_inspector": False,
        "needs_postgres": False,
        "mock_anthropic_response": "Safe migration. Adds a column. Overall risk: LOW",
        "description": "--explain --output json on identical schemas -> JSON, exit 0",
    },
    {
        "name": "explain_rollback_advise_combined",
        "args": ["--explain", "--advise", "EMPTY", "EMPTY", "--rollback"],
        "env": {"ANTHROPIC_API_KEY": "sk-ant-test"},
        "load_config_return": None,
        "mock_anthropic": True,
        "mock_import_error": False,
        "mock_runtime_error": False,
        "mock_inspector": False,
        "needs_postgres": False,
        "mock_anthropic_response": "Safe migration. No destructive changes. Rollback: REVERSE.",
        "description": "--explain --rollback --advise combined -> multiple sections, exit 0",
    },
    {
        "name": "rollback_empty_diff",
        "args": ["EMPTY", "EMPTY", "--rollback"],
        "env": {"ANTHROPIC_API_KEY": "sk-ant-test"},
        "load_config_return": None,
        "mock_anthropic": True,
        "mock_import_error": False,
        "mock_runtime_error": False,
        "mock_inspector": False,
        "needs_postgres": False,
        "mock_anthropic_response": "Rollback: CREATE TABLE public.users (id INT);",
        "description": "--rollback on identical schemas -> 'No differences', exit 0",
    },
    {
        "name": "advise_empty_diff",
        "args": ["--advise", "EMPTY", "EMPTY"],
        "env": {"ANTHROPIC_API_KEY": "sk-ant-test"},
        "load_config_return": None,
        "mock_anthropic": True,
        "mock_import_error": False,
        "mock_runtime_error": False,
        "mock_inspector": False,
        "needs_postgres": False,
        "mock_anthropic_response": "Migration is LOW risk. No destructive operations detected.",
        "description": "--advise on identical schemas -> 'No differences', exit 0",
    },
    {
        "name": "generate_success",
        "args": ["--generate", "add an email column to users", "EMPTY"],
        "env": {"ANTHROPIC_API_KEY": "sk-ant-test"},
        "load_config_return": None,
        "mock_anthropic": True,
        "mock_import_error": False,
        "mock_runtime_error": False,
        "mock_inspector": False,
        "needs_postgres": False,
        "mock_anthropic_response": "ALTER TABLE public.users ADD COLUMN email TEXT;",
        "description": "--generate with description -> generated SQL, exit 0",
    },
    {
        "name": "explain_drift_success",
        "args": [
            "--explain-drift",
            "--from-db",
            "postgresql://localhost/old",
            "--to-db",
            "postgresql://localhost/new",
            "--api-key",
            "sk-ant-test",
        ],
        "env": {},
        "load_config_return": None,
        "mock_anthropic": True,
        "mock_import_error": False,
        "mock_runtime_error": False,
        "mock_inspector": True,
        "needs_postgres": False,
        "mock_anthropic_response": "Schema Drift Analysis: old -> new\nDetected: 2 new tables, 1 removed column.",
        "description": "--explain-drift with mocked inspector -> drift analysis text, exit 0",
    },
    # ============================================================
    # RICH-OUTPUT SCENARIOS — --from-file with real fixtures + Postgres
    # ============================================================
    {
        "name": "explain_with_file_everything",
        "args": [
            "--explain",
            "--unsafe",
            "--from-file",
            "tests/FIXTURES/everything/a.sql",
            "tests/FIXTURES/everything/b.sql",
        ],
        "env": {"ANTHROPIC_API_KEY": "sk-ant-test"},
        "load_config_return": None,
        "mock_anthropic": True,
        "mock_import_error": False,
        "mock_runtime_error": False,
        "mock_inspector": False,
        "needs_postgres": True,
        "mock_anthropic_response": "This migration adds several tables and columns. Overall risk: MEDIUM",
        "description": "--explain --unsafe --from-file with everything fixture -> migration SQL + AI text",
    },
    {
        "name": "explain_json_with_file_everything",
        "args": [
            "--explain",
            "--output",
            "json",
            "--unsafe",
            "--from-file",
            "tests/FIXTURES/everything/a.sql",
            "tests/FIXTURES/everything/b.sql",
        ],
        "env": {"ANTHROPIC_API_KEY": "sk-ant-test"},
        "load_config_return": None,
        "mock_anthropic": True,
        "mock_import_error": False,
        "mock_runtime_error": False,
        "mock_inspector": False,
        "needs_postgres": True,
        "mock_anthropic_response": "This migration adds several tables and columns. Overall risk: MEDIUM",
        "description": "--explain --output json with everything fixture -> JSON with explanation",
    },
    {
        "name": "rollback_with_file_everything",
        "args": [
            "--rollback",
            "--unsafe",
            "--from-file",
            "tests/FIXTURES/everything/a.sql",
            "tests/FIXTURES/everything/b.sql",
        ],
        "env": {"ANTHROPIC_API_KEY": "sk-ant-test"},
        "load_config_return": None,
        "mock_anthropic": True,
        "mock_import_error": False,
        "mock_runtime_error": False,
        "mock_inspector": False,
        "needs_postgres": True,
        "mock_anthropic_response": "DROP TABLE public.new_table; ALTER TABLE public.users DROP COLUMN email;",
        "description": "--rollback --unsafe with everything fixture -> migration SQL + rollback text",
    },
    {
        "name": "advise_with_file_everything",
        "args": [
            "--advise",
            "--unsafe",
            "--from-file",
            "tests/FIXTURES/everything/a.sql",
            "tests/FIXTURES/everything/b.sql",
        ],
        "env": {"ANTHROPIC_API_KEY": "sk-ant-test"},
        "load_config_return": None,
        "mock_anthropic": True,
        "mock_import_error": False,
        "mock_runtime_error": False,
        "mock_inspector": False,
        "needs_postgres": True,
        "mock_anthropic_response": "Migration risk assessment: LOW. All changes are additive.",
        "description": "--advise --unsafe with everything fixture -> migration SQL + advisory text",
    },
    {
        "name": "explain_rollback_advise_with_file_enumdeps",
        "args": [
            "--explain",
            "--rollback",
            "--advise",
            "--unsafe",
            "--from-file",
            "tests/FIXTURES/enumdeps/a.sql",
            "tests/FIXTURES/enumdeps/b.sql",
        ],
        "env": {"ANTHROPIC_API_KEY": "sk-ant-test"},
        "load_config_return": None,
        "mock_anthropic": True,
        "mock_import_error": False,
        "mock_runtime_error": False,
        "mock_inspector": False,
        "needs_postgres": True,
        "mock_anthropic_response": "Combined: explain + rollback + advise for enum dependency changes.",
        "description": "--explain --rollback --advise with enumdeps fixture -> multi-section",
    },
    {
        "name": "generate_with_file_everything",
        "args": [
            "--generate",
            "add a created_at timestamp column to all tables",
            "--unsafe",
            "--from-file",
            "tests/FIXTURES/everything/a.sql",
            "tests/FIXTURES/everything/b.sql",
        ],
        "env": {"ANTHROPIC_API_KEY": "sk-ant-test"},
        "load_config_return": None,
        "mock_anthropic": True,
        "mock_import_error": False,
        "mock_runtime_error": False,
        "mock_inspector": False,
        "needs_postgres": False,
        "mock_anthropic_response": "ALTER TABLE public.users ADD COLUMN created_at TIMESTAMPTZ DEFAULT NOW();",
        "description": "--generate with --from-file and schema context -> generated SQL",
    },
]
